homeassistant:
  packages: !include_dir_named packages

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies: 192.168.0.0/24

recorder:
  purge_keep_days: 90
  exclude:
    entity_globs:
      - sensor.openwb_chargepoint_*_spannung_l*
      - sensor.openwb_chargepoint_*_frequenz
      - sensor.flat*_grid_percentage
      - sensor.heatpump_grid_percentage

influxdb:
  host: !secret influx_host
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influx_pwd
  max_retries: 3
  default_measurement: state
  include:
    entity_globs:
      - sensor.*_production
      - sensor.*_consumption
      - sensor.gridbuyenergy
      - sensor.gridsellenergy

pyscript:
  allow_all_imports: true
  apps:
    meters_persist:
      - dbhost: !secret influx_host
        dbpassword: !secret influx_pwd
    meters_calculate_incs:
      - dbhost: !secret influx_host
        dbpassword: !secret influx_pwd

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
alert: !include alerts.yaml
