automation:
  - id: photovoltaik_surplus_heating_on
    alias: Photovoltaik Surplus Heating On
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - sensor.ebusd_hmu_statuscode
        to: "Warm Water: Compressor active"
      - trigger: state
        entity_id:
          - sensor.ebusd_hmu_statuscode
        to: "Heating: Compressor active"
        for:
          hours: 0
          minutes: 0
          seconds: 0
      - trigger: sun
        event: sunset
        offset: "-5:00"
      - trigger: numeric_state
        entity_id:
          - sensor.esssoc
        above: 20
    conditions:
      - condition: state
        entity_id: input_boolean.heating_on_off
        state: "on"
      - condition: numeric_state
        entity_id: sensor.esssoc
        above: 20
      - condition: numeric_state
        entity_id: sensor.solcast_pv_forecast_forecast_next_x_hours
        above: 5.5
      - condition: sun
        before: sunset
        before_offset: "-3:00"
        after: sunrise
      - condition: numeric_state
        entity_id: sensor.ebusd_ctlv2_displayedoutsidetemp_value
        above: 0
      - condition: numeric_state
        entity_id: input_number.flat_temperature_setpoint
        below: 22
    actions:
      - action: input_number.set_value
        target:
          entity_id: input_number.flat_temperature_setpoint
        data:
          value: 21
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      - action: automation.trigger
        metadata: {}
        data:
          skip_condition: false
        target:
          entity_id: automation.heating_power_auto
      - action: !secret notify_admin
        metadata: {}
        data:
          message: Gebäude Überheizung ein
      - delay:
          hours: 0
          minutes: 15
          seconds: 0
          milliseconds: 0
      - action: input_number.set_value
        target:
          entity_id: input_number.flat_temperature_setpoint
        data:
          value: 22
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      - action: automation.trigger
        metadata: {}
        data:
          skip_condition: false
        target:
          entity_id: automation.heating_power_auto
    mode: single
