automation:
  - id: photovoltaik_surplus_hotwater
    alias: Photovoltaik Surplus Hotwater
    description: ""
    trigger:
      # Trigger automation immediately whenever compressor starts for hotwater
      - trigger: state
        entity_id:
          - sensor.ebusd_hmu_statuscode
        to: "Warm Water: Compressor active"
      # Trigger also when compressor has been running for heating for 45 mins
      - trigger: state
        entity_id:
          - sensor.ebusd_hmu_statuscode
        to: "Heating: Compressor active"
        for:
          hours: 0
          minutes: 45
          seconds: 0
      # Trigger once 4 hours before sunset
      - trigger: sun
        event: sunset
        offset: "-4:00"
      # Trigger when Soc is above 70%
      - trigger: numeric_state
        entity_id:
          - sensor.esssoc
        above: 70
    condition:
      # if PV batterie has at least 70%
      - condition: numeric_state
        entity_id: sensor.esssoc
        above: 70
      # and if PV forecast for the next 2h is above 5 kWh
      - condition: numeric_state
        entity_id: sensor.solcast_pv_forecast_forecast_next_x_hours
        above: 5
      # and if it is at least 3h before sunset but after sunrise
      - condition: sun
        before: sunset
        before_offset: "-3:00"
        after: sunrise
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: input_number.flat_temperature_setpoint
            above: 20
          - condition: numeric_state
            entity_id: sensor.flats_heating_demand
            below: 0
      # and if either the compressor is already running
      # or hot water is below 45 °C
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: water_heater.ctlv2_hotwater_vaillant
            attribute: current_temperature
            below: 45
          - condition: state
            entity_id: sensor.ebusd_hmu_statuscode
            state: "Warm Water: Compressor active"
          - condition: state
            entity_id: sensor.ebusd_hmu_statuscode
            state: "Heating: Compressor active"
    action:
      # then use the script to change hotwater settings for overheating
      - action: script.warmwater_settings
        metadata: {}
        data:
          setpoint: 60
          maxchargetime: 150
          chargehysteresis: 5
          opmode: "heat"
          hwcmode: "normal"
          restore: 1
          timeout: 150
      # send out notification on success or failure
      - if:
          - condition: numeric_state
            entity_id: sensor.ebusd_ctlv2_hwcstoragetemp_value
            below: 60
        then:
          - service: !secret notify_admin
            data:
              message: >-
                PV Überschuss WW abgebrochen mit {{
                states('sensor.ebusd_ctlv2_hwcstoragetemp_value')}}
    mode: single
