automation:
  - id: photovoltaik_surplus_hotwater
    alias: Photovoltaik Surplus Hotwater
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.ebusd_hmu_statuscode
        to: "Warm Water: Compressor active"
      - platform: state
        entity_id:
          - sensor.ebusd_hmu_statuscode
        to: "Heating: Compressor active"
        for:
          hours: 0
          minutes: 45
          seconds: 0
      - platform: sun
        event: sunset
        offset: "-4:00"
    condition:
      - condition: numeric_state
        entity_id: sensor.esssoc
        above: 90
      - condition: numeric_state
        entity_id: sensor.solcast_pv_forecast_forecast_next_x_hours
        above: 5
      - condition: sun
        before: sunset
        before_offset: "-3:00"
        after: sunrise
      - condition: numeric_state
        entity_id: sensor.flats_heating_demand
        below: 0
      - condition: numeric_state
        entity_id: water_heater.ctlv2_hotwater_vaillant
        attribute: current_temperature
        below: 45
    action:
      - action: script.warmwater_settings
        metadata: {}
        data:
          setpoint: 60
          maxchargetime: 150
          chargehysteresis: 13
          opmode: "heat"
          restore: 1
          timeout: 150
      - if:
          - condition: numeric_state
            entity_id: sensor.ebusd_ctlv2_hwcstoragetemp_tempv
            below: 60
        then:
          - service: !secret notify_admin
            data:
              message: >-
                PV Überschuss WW abgebrochen mit {{
                states('sensor.ebusd_ctlv2_hwcstoragetemp_tempv')}}
    mode: single
