automation:
  - id: photovoltaik_surplus_heating_off
    alias: Photovoltaik Surplus Heating off
    description: ""
    triggers:
      - trigger: numeric_state
        entity_id:
          - sensor.esssoc
        below: 10
      - trigger: numeric_state
        entity_id:
          - sensor.solcast_pv_forecast_forecast_next_x_hours
        below: 3
      - trigger: sun
        event: sunset
        offset: "-1:00"
      - trigger: numeric_state
        entity_id:
          - sensor.ebusd_ctlv2_displayedoutsidetemp_value
        below: 2
    conditions:
      - condition: state
        entity_id: input_boolean.heating_on_off
        state: "on"
      - condition: numeric_state
        entity_id: input_number.flat_temperature_setpoint
        above: 20
    actions:
      - action: input_number.set_value
        target:
          entity_id: input_number.flat_temperature_setpoint
        data:
          value: 20
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      - action: automation.trigger
        metadata: {}
        data:
          skip_condition: false
        target:
          entity_id: automation.heating_power_auto
      - action: !secret notify_admin
        metadata: {}
        data:
          message: Gebäude Überheizung aus
    mode: single
