automation:
  - id: hotwater_2_transitiontime
    alias: Hotwater Transition Time Mode
    description: ""
    triggers:
      - trigger: numeric_state
        entity_id:
          - sensor.ebusd_ctlv2_displayedoutsidetemp_value
        for:
          hours: 0
          minutes: 15
          seconds: 0
        below: number.ebusd_ctlv2_hc1summertemplimit_value
      - trigger: numeric_state
        entity_id:
          - sensor.ebusd_ctlv2_displayedoutsidetemp_value
        for:
          hours: 0
          minutes: 15
          seconds: 0
        above: 6
    conditions:
      - condition: state
        entity_id: input_boolean.heating_on_off
        state: "on"
    actions:
      - action: script.warmwater_settings
        metadata: {}
        data:
          setpoint: 40
          maxchargetime: 60
          chargehysteresis: 10
          opmode: "auto"
          hwcmode: "eco"
          restore: 0
          timeout: 0
      - service: !secret notify_admin
        metadata: {}
        data:
          message: Warmwasser Transition low
    mode: single
