automation:
  - id: hotwater_0_summer
    alias: Hotwater Summer Mode
    description: ""
    trigger: []
    condition:
      - condition: state
        entity_id: input_boolean.heating_on_off
        state: "off"
    action:
      - action: script.warmwater_settings
        metadata: {}
        data:
          setpoint: 55
          maxchargetime: 120
          chargehysteresis: 25
          opmode: "auto"
          hwcmode: "eco"
          restore: 0
          timeout: 0
      - service: !secret notify_admin
        metadata: {}
        data:
          message: Warmwasser Sommer
    mode: single
