automation:
  - id: hotwater_legio_lastrun
    alias: "Hotwater Legio Lastrun"
    description: ""
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.ebusd_ctlv2_hwcstoragetemp_tempv
        for:
          hours: 0
          minutes: 1
          seconds: 0
        above: 60
    action:
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.hotwater_legio_lastrun
        data:
          date: "{{ now().strftime('%Y-%m-%d') }}"
      - service: !secret notify_admin
        data:
          message: Legio Termperatur erreicht mit {{ states('sensor.ebusd_ctlv2_hwcstoragetemp_tempv')}}
    mode: single
