automation:
  - id: hotwater_legio
    alias: "Hotwater Legio"
    description: ""
    trigger:
      - platform: time
        at: "13:00:00"
    condition:
      - condition: numeric_state
        entity_id: sensor.hotwater_legio_days_since_lastrun
        above: 25
      - condition: numeric_state
        entity_id: sensor.ebusd_ctlv2_displayedoutsidetemp_tempv
        above: 10
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.ebusd_ctlv2_displayedoutsidetemp_tempv
            above: 15
          - condition: and
            conditions:
              # if PV batterie has at least 20%
              - condition: numeric_state
                entity_id: sensor.esssoc
                above: 20
              # and if PV forecast for the next 2h is above 5 kWh
              - condition: numeric_state
                entity_id: sensor.solcast_pv_forecast_forecast_next_x_hours
                above: 5
      - condition: numeric_state
        entity_id: sensor.flats_heating_demand
        below: 0.1
    action:
      # Enable parallel load?
      # Lower HwcBivalencePoint to enable parallel heater 
      - action: script.warmwater_settings
        metadata: {}
        data:
          setpoint: 60
          maxchargetime: 150
          chargehysteresis: 5
          opmode: "heat"
          hwcmode: "normal"
          restore: 1
          timeout: 150
      - if:
          - condition: numeric_state
            entity_id: sensor.ebusd_ctlv2_hwcstoragetemp_tempv
            below: 60
        then:
          - service: !secret notify_admin
            data:
              message: Legio Schaltung abgebrochen mit {{ states('sensor.ebusd_ctlv2_hwcstoragetemp_tempv')}}
    mode: single
