automation:
  - id: heating_bath_window_open
    alias: "Heating Bath Window Open"
    description: ""
    trigger:
      - trigger: state
        entity_id:
          - binary_sensor.fenster_bad_alarm
        from:
          - "off"
        to:
          - "on"
        for:
          hours: 0
          minutes: 15
          seconds: 0
    conditions:
      - condition: state
        entity_id: input_boolean.heating_on_off
        state: "on"
    action:
      - service: !secret notify_all
        data:
          message: Fenster im Bad offen
    mode: single
