automation:
  - id: heating_heatcurve
    alias: Heating Change Heatcurve
    description: ""
    trigger:
      - platform: state
        entity_id:
          - input_number.heating_hc1_heating_curve
    condition: []
    action:
      - service: mqtt.publish
        data:
          qos: "0"
          retain: false
          topic: ebusd/ctlv2/Hc1HeatCurve/set
          payload_template: "{{ states('input_number.heating_hc1_heating_curve') }}"
    mode: single
