sensor:
  - platform: template
    sensors:
      grid_percentage:
        friendly_name: "Verbrauchsanteil Netz"
        unique_id: grid_percentage
        device_class: power_factor
        value_template: >
          {% if has_value('sensor.consumptionpower') %}
            {% set power = max(0, states('sensor.consumptionpower') | float) %}
            {% set grid_power = ( max(0, states('sensor.gridpower') | float) ) | round(0, "half", default=0) %}
            {% if power > 0 %}
            {% set grid_factor = max(0,min(1,(grid_power / power))) %}
            {{ grid_factor * 100 }}
            {% else %}
            0
            {% endif %}
          {% endif %}
